### ISSUE TITLE
try to build it on debian 8.0

### ISSUE THREAD

**Issue by yoyz** [mtytel/twytch#1]
Hi,

Not a real issue, I had try do build it on my debian 8.
I've git clone the master version in my ~/build dir : sha c652a78537d1ad44d5b00d07925fdd10c589ca62.
Download the lastest version of juce from here : http://www.juce.com/download and unzip it in my ~/build/JUCE dir.

Do some ln -s stuff.
```bash
yoyz@yoyz-laptop:~/build/twytch/ ln -s ../JUCE .
```

Then try to build it : 
```bash
yoyz@yoyz-laptop:~/build/twytch/ cd standalone/builds/linux/
yoyz@yoyz-laptop:~/build/twytch/standalone/builds/linux/ make
```

I fall into something like src not sync, and I don't know if I use the right juce version.

```bash
   yoyz@yoyz-laptop:~/build/twytch/standalone/builds/linux/ make
   Compiling modulation_slider.cpp
   ../../../src/editor_components/modulation_slider.cpp: In constructor    ‘ModulationSlider::ModulationSlider(TwytchSlider*)’:
   ../../../src/editor_components/modulation_slider.cpp:35:22: error: ‘class TwytchSlider’ has no    member named ‘isRotary’
        if (destination->isRotary())
                      ^
Makefile:365: recipe for target 'build/intermediate/Debug/modulation_slider_aee8aab8.o' failed
make: *** [build/intermediate/Debug/modulation_slider_aee8aab8.o] Error 1
```
It seem "isRotary()" is defined in "class Slider::Pimpl" in the modules/juce_gui_basics/widgets/juce_Slider.cpp file. 

If you can tag a version which can be build easily, i'd like to test it :)

**Comment by mtytel** [comment]
hmmm... I believe I'm using the development version of JUCE.
I'm just on the master branch here: https://github.com/julianstorer/JUCE

I actually might be moving over to this fork soon which has LV2 plugin building: https://github.com/DISTRHO/juce

**Comment by mtytel** [comment]
I'm actually working on a debian package as we speak. :) The documentation could be a novel though it's so long. Might take a bit of time to get through because it's my first time.

**Comment by yoyz** [comment]
Great, let me know when you want me to try it. I'll be happy to play with.

Envoyé de mon iPhone

**Comment by mtytel** [comment]
Got a build up! You can download a deb package at http://tytel.org/twtych
Love to know what you think so far :) just FYI, the formant filter and stutter effect are not in a stable state so I wouldn't turn them on just yet.

There's also a ppa, works for me but I don't think anyone else has downloaded it from here so I'm not sure it works: ppa:tytel/twytch

**Comment by yoyz** [comment]
Great I will try it this week !

Envoyé de mon iPhone

**Comment by yoyz** [comment]
Hi Matt,

I've try the windows version for one hours and it can produce really nice sound, will try the debian on my laptop this week.

I've try many parameters and my first feeling are : 
- definitely great sound can be produce with it and today I've enjoy it a lot ; 

Now some comments and feedback :
- something need to be done on "RESAMP" in the STUTTER, after 1/4 it doesn't do anything anymore, and it's a good "effect" ; 
- The main filter in LPF sound to digital when the Fc is low, the Q is high and the note is really low, at this moment it sound too "digital", don't know if it is the correct word, if the Q is reduced a bit, it sound good again  ; 
- I don't have any opinion on the "Feedback" blocks, but the Saturation parameter seem to be too agressive ; 
- The "cross_mod" and unisson are really perfect and whoooaa ; 
- There is some automation function but they are not easy to use and to "reset" ;
- The portamento mode auto and on reset the enveloppe, I use my laptop keyboard, don't know if it do the same with a midi one ;  
- I have to modify a parameter to produce the first sound, when I exit and relaunch again ; 
- Maybe put a desktop links and a menu links to help users to find it, for me it was in "program files".

Definitely it's a great works and it sound really sweat :)

**Comment by mtytel** [comment]
Thanks for the awesome feedback! Sorry it took a while to respond, I've been biking down the coast of California for the past few days.

Yea the stutter needs a lot of work. It's going to change a lot, mostly just a place holder right now.

I'm not sure what to do about the digital sounding filter right now. I'll probably make some improvements to the sound in the future but there's a lot other stuff to do and this is a really open ended problem that takes a lot of experimentation. 

I'll see what I can do about the saturation. That knob just boosts the signal before it is sent into a distortion. The distortion is pretty simple right now and it gives a really harsh sound so I can make some changes there.

I like the cross mod but it only creates higher frequencies, it would be nice if it created some subharmonics as well so i'm going to tweak it a bit.

Yea, right now you double click on the modulation knob to reset it. Might change that and have a little (x) you can click as well. You can also right click on the modulation buttons to disconnect it from a specific destination or right click on a knob to disconnect it from a specific source.

I think you're looking for "Legato" to not reset the envelopes? Also if the polyphony is high every new voice gets a new envelope.

For some reason on Windows you have to click on the interface to give it focus before it will make sound. I must be doing something wrong with JUCE to request focus.

Yea the windows installer is really bare right now. I'm just learning Wix right now so it'll be more friendly in the future.

Thanks for testing it out :dancer:
